export function generateSlug() {
  const adjective = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)]
  return `${adjective}-${noun}`
}

// Credit for the list of adjectives and nouns
// https://gist.github.com/ioistired/fb6ac96bad2e840f36b9ec53cc3f7a2a

const ADJECTIVES = [
  'animated',
  'automatic',
  'bookish',
  'bug-free',
  'cautious',
  'congenial',
  'crispy',
  'cuddly',
  'curly',
  'didactic',
  'effective',
  'expert',
  'fantastic',
  'fictional',
  'fluffy',
  'friendly',
  'furry',
  'fuzzy',
  'glowing',
  'ideal',
  'improved',
  'jubilant',
  'laughing',
  'legendary',
  'literate',
  'miniature',
  'musical',
  'potential',
  'probable',
  'psychic',
  'redesigned',
  'refactored',
  'reimagined',
  'scaling',
  'shiny',
  'silver',
  'solid',
  'special',
  'studious',
  'stunning',
  'sturdy',
  'super',
  'super-duper',
  'supreme',
  'symmetrical',
  'turbo',
  'ubiquitous',
  'upgraded',
  'urban',
  'verbose',
  'vigilant'
] as const

const NOUNS = [
  'adventure',
  'barnacle',
  'bassoon',
  'broccoli',
  'carnival',
  'chainsaw',
  'computing-machine',
  'couscous',
  'disco',
  'dollop',
  'doodle',
  'engine',
  'enigma',
  'eureka',
  'fiesta',
  'fortnight',
  'funicular',
  'garbanzo',
  'giggle',
  'goggles',
  'guacamole',
  'guide',
  'happiness',
  'invention',
  'journey',
  'lamp',
  'meme',
  'memory',
  'palm-tree',
  'pancake',
  'parakeet',
  'potato',
  'robot',
  'rotary-phone',
  'sniffle',
  'spoon',
  'spork',
  'succotash',
  'system',
  'telegram',
  'train',
  'tribble',
  'umbrella',
  'waddle',
  'waffle',
  'winner'
] as const
